// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/app": {
    params: {};
  };
  "/app/dashboard": {
    params: {};
  };
  "/app/transactions": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/signup" | "/app" | "/app/dashboard" | "/app/transactions";
  };
  "routes/Landing.tsx": {
    id: "routes/Landing";
    page: "/";
  };
  "routes/LogIn.tsx": {
    id: "routes/LogIn";
    page: "/login";
  };
  "routes/SignUp.tsx": {
    id: "routes/SignUp";
    page: "/signup";
  };
  "layouts/ProtectedLayout.tsx": {
    id: "layouts/ProtectedLayout";
    page: "/app" | "/app/dashboard" | "/app/transactions";
  };
  "layouts/AppLayout.tsx": {
    id: "layouts/AppLayout";
    page: "/app" | "/app/dashboard" | "/app/transactions";
  };
  "routes/Dashboard.tsx": {
    id: "routes/Dashboard";
    page: "/app/dashboard";
  };
  "routes/Transactions.tsx": {
    id: "routes/Transactions";
    page: "/app/transactions";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/Landing": typeof import("./app/routes/Landing.tsx");
  "routes/LogIn": typeof import("./app/routes/LogIn.tsx");
  "routes/SignUp": typeof import("./app/routes/SignUp.tsx");
  "layouts/ProtectedLayout": typeof import("./app/layouts/ProtectedLayout.tsx");
  "layouts/AppLayout": typeof import("./app/layouts/AppLayout.tsx");
  "routes/Dashboard": typeof import("./app/routes/Dashboard.tsx");
  "routes/Transactions": typeof import("./app/routes/Transactions.tsx");
};