// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/app": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/signup" | "/app";
  };
  "routes/Landing.tsx": {
    id: "routes/Landing";
    page: "/";
  };
  "routes/LogIn.tsx": {
    id: "routes/LogIn";
    page: "/login";
  };
  "routes/SignUp.tsx": {
    id: "routes/SignUp";
    page: "/signup";
  };
  "layouts/ProtectedLayout.tsx": {
    id: "layouts/ProtectedLayout";
    page: "/app";
  };
  "routes/App.tsx": {
    id: "routes/App";
    page: "/app";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/Landing": typeof import("./app/routes/Landing.tsx");
  "routes/LogIn": typeof import("./app/routes/LogIn.tsx");
  "routes/SignUp": typeof import("./app/routes/SignUp.tsx");
  "layouts/ProtectedLayout": typeof import("./app/layouts/ProtectedLayout.tsx");
  "routes/App": typeof import("./app/routes/App.tsx");
};